export default [
  {
    plate: '煤炭',
    stock: '中证煤炭',
    id: 'SZ399998',
    fund: '富国中证煤炭指数C',
  },
  {
    plate: '有色',
    stock: '有色龙头ETF',
    id: 'SZ159876',
    fund: '财通资管中证有色金属指数C',
  },
  {
    plate: '农业',
    stock: '中证农业',
    id: 'SH000949',
    fund: '天弘中证农业主题指数C',
  },
  {
    plate: '国防军工',
    stock: '中证军工',
    id: 'SZ399967',
    fund: '广发中证军工ETF联接C',
  },
  {
    plate: '地产',
    stock: '地产等权',
    id: 'SZ399983',
    fund: '招商沪深300地产等权重指数C',
  },
  {
    plate: '证券',
    stock: '证券公司',
    id: 'SZ399975',
    fund: '天弘中证全指证券公司ETF联接C',
  },
  {
    plate: '小盘',
    stock: '中证1000',
    id: 'SH000852',
    fund: '易方达中证1000ETF联接C',
  },
  {
    plate: '食品',
    stock: '细分食品',
    id: 'SH000815',
    fund: '华宝中证细分食品饮料ETF联接C',
  },
  {
    plate: '半导体',
    stock: '芯片ETF',
    id: 'SH516920',
    fund: '天弘中证芯片产业指数C',
  },
  {
    plate: '传媒',
    stock: '中证传媒',
    id: 'SZ399971',
    fund: '鹏华中证传媒指数C',
  },
  {
    plate: '医药',
    stock: '生物医药',
    id: 'SZ399441',
    fund: '天弘国证生物医药指数C',
  },
  {
    plate: '恒生科技',
    stock: '恒生科技30ETF',
    id: 'SH513010',
    fund: '华安恒生科技指数C',
  },
  {
    plate: '新能源',
    stock: 'CS新能车',
    id: 'SZ399976',
    fund: '天弘中证新能源车C',
  },
  {
    plate: '家用电器',
    stock: '龙头家电ETF',
    id: 'SZ159730',
    fund: '天弘国证龙头家电指数C',
  },
  {
    plate: '人工智能',
    stock: '人工智能ETF',
    id: 'SZ159819',
    fund: '易方达中证人工智能主题ETF联接C',
  },
  {
    plate: '创业板50',
    stock: '创业板50',
    id: 'SZ399673',
    fund: '易方达创业板50ETF联接C',
  },
  {
    plate: '中药',
    stock: '中药ETF',
    id: 'SZ159647',
    fund: '鹏华中证中药ETF联接C',
  },
  {
    plate: '纳斯达克',
    stock: '纳指ETF',
    id: 'SZ159941',
    fund: '华安纳斯达克100指数C',
  },
  {
    plate: '红利',
    stock: '中证红利',
    id: 'SH000922',
    fund: '易方达中证红利ETF联接C',
  },
  {
    plate: '白酒',
    stock: '中证白酒',
    id: 'SZ399997',
    fund: '招商中证白酒指数C',
  },
]
